// ================================================================
// Données des postes de pêche — Lac de Podensac
// Coordonnées réelles extraites de la carte Google Maps du lac
// ================================================================
const POSTES = [
  {
    id: 1,
    nom: "Poste 1",
    lat: 44.6513675, lng: -0.3413005,
    icon: "🌿",
    description: "Premier poste sur la rive, idéal pour 1 à 2 pêcheurs. Accès facile depuis le parking principal. Fond herbeux favorable à la carpe et à la tanche.",
    poissons: ["Carpe", "Tanche", "Brème"],
    difficulte: "Facile",
    profondeur: "1.5–3m",
    fond: "Herbeux / Vaseux",
    capacite: 2,
    prix_jour: 35,
    prix_nuit: 45,
    prix_24h: 72,
    disponible: true,
    score: 4.6,
    avis: 38,
    acces_pmr: true,
    captures: [
      { espece: "Carpe", poids: "8.4kg", date: "12 mai 2025", emoji: "🐟" },
      { espece: "Tanche", poids: "1.2kg", date: "5 mai 2025", emoji: "🐟" },
      { espece: "Carpe", poids: "11.3kg", date: "28 avr. 2025", emoji: "🐟" },
      { espece: "Brème", poids: "0.8kg", date: "20 avr. 2025", emoji: "🐟" },
    ],
    equipements: ["Banc de pêche", "Anneau d'amarrage", "Accès PMR"],
    zone_ha: 1.20,
    note: "Zone de pêche à la nuitée — 1,20 ha",
  },
  {
    id: 2,
    nom: "Poste 2",
    lat: 44.6518999, lng: -0.342419,
    icon: "🪴",
    description: "Poste spacieux avec 6 emplacements photographiés. Entouré de végétation, excellent pour la pêche à la carpe de nuit. Zone de 1,27 ha réservée.",
    poissons: ["Tanche", "Brème", "Carpe", "Gardon"],
    difficulte: "Facile",
    profondeur: "1–2.5m",
    fond: "Herbeux / Sableux",
    capacite: 2,
    prix_jour: 38,
    prix_nuit: 48,
    prix_24h: 78,
    disponible: false,
    score: 4.4,
    avis: 52,
    acces_pmr: false,
    captures: [
      { espece: "Tanche", poids: "2.1kg", date: "15 mai 2025", emoji: "🐟" },
      { espece: "Carpe", poids: "9.7kg", date: "10 mai 2025", emoji: "🐟" },
      { espece: "Brème", poids: "1.4kg", date: "3 mai 2025", emoji: "🐟" },
      { espece: "Gardon", poids: "0.3kg", date: "25 avr. 2025", emoji: "🐟" },
    ],
    equipements: ["Banc de pêche", "Table de montage", "Panneau espèces"],
    zone_ha: 1.27,
    note: "Zone de pêche à la nuitée — 1,27 ha",
  },
  {
    id: 3,
    nom: "Poste 3",
    lat: 44.6525002, lng: -0.3434805,
    icon: "🦆",
    description: "Poste en rive nord avec une belle vue sur le lac. Idéal pour les carnassiers le soir et tôt le matin. Zone de 1,22 ha.",
    poissons: ["Sandre", "Perche", "Brochet"],
    difficulte: "Intermédiaire",
    profondeur: "2–4m",
    fond: "Sableux / Vaseux",
    capacite: 2,
    prix_jour: 40,
    prix_nuit: 52,
    prix_24h: 82,
    disponible: true,
    score: 4.5,
    avis: 27,
    acces_pmr: false,
    captures: [
      { espece: "Sandre", poids: "3.8kg", date: "18 mai 2025", emoji: "🐟" },
      { espece: "Brochet", poids: "4.2kg", date: "14 mai 2025", emoji: "🐟" },
      { espece: "Perche", poids: "0.9kg", date: "8 mai 2025", emoji: "🐟" },
      { espece: "Sandre", poids: "5.1kg", date: "1 mai 2025", emoji: "🐟" },
    ],
    equipements: ["Banc de pêche", "Boîte à appâts", "Carnet captures"],
    zone_ha: 1.22,
    note: "Zone de pêche à la nuitée — 1,22 ha",
  },
  {
    id: 4,
    nom: "Poste 4",
    lat: 44.6530008, lng: -0.3446801,
    icon: "⚓",
    description: "Poste bien équipé avec 2 emplacements photographiés. Fond vaseux favorable à la carpe. Zone de 1,33 ha, idéale pour les séances longues.",
    poissons: ["Carpe", "Brème", "Tanche", "Rotengle"],
    difficulte: "Facile",
    profondeur: "2–3.5m",
    fond: "Vaseux / Herbeux",
    capacite: 2,
    prix_jour: 35,
    prix_nuit: 45,
    prix_24h: 70,
    disponible: true,
    score: 4.3,
    avis: 44,
    acces_pmr: true,
    captures: [
      { espece: "Carpe", poids: "7.6kg", date: "20 mai 2025", emoji: "🐟" },
      { espece: "Brème", poids: "1.1kg", date: "16 mai 2025", emoji: "🐟" },
      { espece: "Tanche", poids: "1.8kg", date: "12 mai 2025", emoji: "🐟" },
      { espece: "Rotengle", poids: "0.25kg", date: "7 mai 2025", emoji: "🐟" },
    ],
    equipements: ["Banc de pêche", "Accès PMR", "Point d'eau proche"],
    zone_ha: 1.33,
    note: "Zone de pêche à la nuitée — 1,33 ha",
  },
  {
    id: 5,
    nom: "Poste 5",
    lat: 44.6534109, lng: -0.3455524,
    icon: "🚧",
    description: "Grand poste de 1,82 ha, actuellement en cours d'aménagement. Ouverture prévue prochainement. Zone prometteuse avec de belles perspectives de captures.",
    poissons: ["Carpe", "Amour blanc", "Tanche"],
    difficulte: "Intermédiaire",
    profondeur: "2–5m",
    fond: "Herbeux / Vaseux",
    capacite: 2,
    prix_jour: 42,
    prix_nuit: 55,
    prix_24h: 88,
    disponible: false,
    score: 4.0,
    avis: 5,
    acces_pmr: false,
    captures: [
      { espece: "Carpe", poids: "10.2kg", date: "Test 2025", emoji: "🐟" },
      { espece: "Amour blanc", poids: "8.5kg", date: "Test 2025", emoji: "🐟" },
      { espece: "Tanche", poids: "2.1kg", date: "Test 2025", emoji: "🐟" },
      { espece: "Carpe", poids: "13.0kg", date: "Test 2025", emoji: "🐟" },
    ],
    equipements: ["En cours d'aménagement", "Ouverture prochaine"],
    zone_ha: 1.82,
    note: "Poste pas encore créé — Zone 1,82 ha",
    coming_soon: true,
  },
  {
    id: 6,
    nom: "Poste 6",
    lat: 44.6539859, lng: -0.3473511,
    icon: "🌊",
    description: "Grand poste de 2,52 ha, le plus vaste du lac. Accueille 2 à 3 pêcheurs. Vue panoramique sur toute la longueur du lac. Zone à la nuitée.",
    poissons: ["Carpe", "Sandre", "Brochet", "Amour blanc"],
    difficulte: "Intermédiaire",
    profondeur: "2.5–5m",
    fond: "Sableux / Vaseux",
    capacite: 3,
    prix_jour: 45,
    prix_nuit: 58,
    prix_24h: 92,
    disponible: true,
    score: 4.7,
    avis: 61,
    acces_pmr: false,
    captures: [
      { espece: "Carpe", poids: "14.8kg", date: "21 mai 2025", emoji: "🐟" },
      { espece: "Sandre", poids: "4.7kg", date: "17 mai 2025", emoji: "🐟" },
      { espece: "Brochet", poids: "5.2kg", date: "13 mai 2025", emoji: "🐟" },
      { espece: "Amour blanc", poids: "11.3kg", date: "9 mai 2025", emoji: "🐟" },
    ],
    equipements: ["Banc de pêche (2-3 pêcheurs)", "Grande zone de pose", "Épuisette géante"],
    zone_ha: 2.52,
    note: "Zone de pêche à la nuitée — 2,52 ha — 2 à 3 pêcheurs",
  },
  {
    id: 7,
    nom: "Poste 7 — Ponton Bois",
    lat: 44.6526519, lng: -0.3495224,
    icon: "🪵",
    description: "Poste avec ponton en bois de 22m². Plateforme stable et confortable surplombant l'eau. Accès direct depuis le parking central. Vue imprenable sur le lac.",
    poissons: ["Carpe", "Tanche", "Brème", "Perche"],
    difficulte: "Facile",
    profondeur: "1.5–3m",
    fond: "Vaseux",
    capacite: 2,
    prix_jour: 42,
    prix_nuit: 54,
    prix_24h: 85,
    disponible: true,
    score: 4.8,
    avis: 73,
    acces_pmr: true,
    captures: [
      { espece: "Carpe", poids: "12.1kg", date: "22 mai 2025", emoji: "🐟" },
      { espece: "Tanche", poids: "2.4kg", date: "18 mai 2025", emoji: "🐟" },
      { espece: "Brème", poids: "1.9kg", date: "14 mai 2025", emoji: "🐟" },
      { espece: "Perche", poids: "0.8kg", date: "10 mai 2025", emoji: "🐟" },
    ],
    equipements: ["Ponton bois 22m²", "Accès PMR", "Anneau d'amarrage", "Éclairage nocturne", "Table de préparation"],
    note: "Ponton bois 22m² — Accès voiture possible",
    premium: false,
  },
  {
    id: 8,
    nom: "Poste 8 — Des Barques",
    lat: 44.6533971, lng: -0.3515996,
    icon: "⛵",
    description: "Poste situé près de l'aire des barques. En cours de finalisation. Accès aux embarcations (barques, canoës) à proximité immédiate. Zone idéale pour combiner pêche depuis la rive et depuis l'eau.",
    poissons: ["Carpe", "Sandre", "Anguille"],
    difficulte: "Intermédiaire",
    profondeur: "2–4m",
    fond: "Vaseux / Limoneux",
    capacite: 2,
    prix_jour: 40,
    prix_nuit: 52,
    prix_24h: 82,
    disponible: false,
    score: 4.2,
    avis: 12,
    acces_pmr: false,
    captures: [
      { espece: "Carpe", poids: "9.3kg", date: "20 mai 2025", emoji: "🐟" },
      { espece: "Sandre", poids: "3.6kg", date: "16 mai 2025", emoji: "🐟" },
      { espece: "Anguille", poids: "1.7kg", date: "11 mai 2025", emoji: "🐍" },
      { espece: "Carpe", poids: "7.8kg", date: "5 mai 2025", emoji: "🐟" },
    ],
    equipements: ["En cours de finalisation", "Proximité barques & canoës", "Rampe de mise à l'eau à 50m"],
    note: "Poste pas encore terminé — proche de l'aire barques",
    coming_soon: true,
  },
  {
    id: 9,
    nom: "Poste 9 — De la Cale",
    lat: 44.653821, lng: -0.3522097,
    icon: "🏗️",
    description: "Poste accessible en voiture toute l'année grâce à sa rampe bétonnée (la cale). Idéal pour les pêcheurs qui amènent beaucoup de matériel. Proche des sanitaires et de la table de pique-nique.",
    poissons: ["Carpe", "Tanche", "Brème", "Sandre"],
    difficulte: "Facile",
    profondeur: "1.5–3.5m",
    fond: "Sableux / Béton",
    capacite: 2,
    prix_jour: 38,
    prix_nuit: 50,
    prix_24h: 78,
    disponible: true,
    score: 4.5,
    avis: 29,
    acces_pmr: true,
    captures: [
      { espece: "Carpe", poids: "11.5kg", date: "23 mai 2025", emoji: "🐟" },
      { espece: "Tanche", poids: "2.0kg", date: "19 mai 2025", emoji: "🐟" },
      { espece: "Sandre", poids: "4.1kg", date: "15 mai 2025", emoji: "🐟" },
      { espece: "Brème", poids: "1.6kg", date: "9 mai 2025", emoji: "🐟" },
    ],
    equipements: ["Accès voiture année", "Rampe de mise à l'eau", "WC à proximité", "Table pique-nique / BBQ", "Parking dédié"],
    note: "Accès possible toute l'année en voiture",
  },
  {
    id: 10,
    nom: "Poste 10 — Des Iris",
    lat: 44.6541539, lng: -0.3527693,
    icon: "🌸",
    description: "Poste nommé pour ses magnifiques iris en fleurs au printemps. Accès voiture à 30m. Zone de 'toutes pêches' à proximité — carnassiers et pêche de rive. L'un des postes les plus esthétiques du lac.",
    poissons: ["Carpe", "Sandre", "Brochet", "Tanche", "Anguille"],
    difficulte: "Intermédiaire",
    profondeur: "2–5m",
    fond: "Herbeux / Vaseux",
    capacite: 2,
    prix_jour: 42,
    prix_nuit: 55,
    prix_24h: 88,
    disponible: true,
    score: 4.9,
    avis: 41,
    acces_pmr: false,
    captures: [
      { espece: "Sandre", poids: "6.8kg", date: "22 mai 2025", emoji: "🐟" },
      { espece: "Brochet", poids: "7.4kg", date: "17 mai 2025", emoji: "🐟" },
      { espece: "Carpe", poids: "16.2kg", date: "12 mai 2025", emoji: "🏆" },
      { espece: "Anguille", poids: "2.1kg", date: "6 mai 2025", emoji: "🐍" },
    ],
    equipements: ["Accès voiture à 30m", "Zone toutes pêches adjacente", "Panneau faune & flore", "Ambiance iris au printemps"],
    note: "Accès à 30m en voiture — Zone toutes pêches à proximité",
    premium: true,
  },
];

// Équipements & points d'intérêt du lac
const AMENITIES = [
  { id: 'parking', nom: 'Parking', lat: 44.6529252, lng: -0.352212, icon: '🅿️', desc: 'Parking principal — Merci de garer vos véhicules ici' },
  { id: 'wc', nom: 'Toilettes', lat: 44.6533223, lng: -0.3519412, icon: '🚻', desc: 'Sanitaires disponibles' },
  { id: 'picnic1', nom: 'Table de pique-nique & BBQ', lat: 44.6532783, lng: -0.3513988, icon: '🍖', desc: 'Table de pique-nique avec barbecue' },
  { id: 'picnic2', nom: 'Table de pique-nique', lat: 44.6537412, lng: -0.3522097, icon: '🌳', desc: 'Table de pique-nique' },
  { id: 'barques', nom: 'Barques & Canoës', lat: 44.6535353, lng: -0.3515685, icon: '🛶', desc: 'Location de barques et canoës' },
  { id: 'rampe', nom: 'Rampe de mise à l\'eau', lat: 44.6537339, lng: -0.3519588, icon: '⛵', desc: 'Rampe bétonnée — accès toute l\'année' },
];

// Centre approximatif du lac
const LAC_CENTER = [44.6528, -0.3470];
const LAC_ZOOM = 15;

// Rend le tableau disponible globalement
window.POSTES = POSTES;
window.AMENITIES = AMENITIES;
window.LAC_CENTER = LAC_CENTER;
window.LAC_ZOOM = LAC_ZOOM;
